/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AocLetter {
    'size': number;
    'x': number;
    'y': number;
  }
  interface AocLetterAttributes extends StencilHTMLAttributes {
    'size'?: number;
    'x'?: number;
    'y'?: number;
  }

  interface AocApp {}
  interface AocAppAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AocLetter': Components.AocLetter;
    'AocApp': Components.AocApp;
  }

  interface StencilIntrinsicElements {
    'aoc-letter': Components.AocLetterAttributes;
    'aoc-app': Components.AocAppAttributes;
  }


  interface HTMLAocLetterElement extends Components.AocLetter, HTMLStencilElement {}
  var HTMLAocLetterElement: {
    prototype: HTMLAocLetterElement;
    new (): HTMLAocLetterElement;
  };

  interface HTMLAocAppElement extends Components.AocApp, HTMLStencilElement {}
  var HTMLAocAppElement: {
    prototype: HTMLAocAppElement;
    new (): HTMLAocAppElement;
  };

  interface HTMLElementTagNameMap {
    'aoc-letter': HTMLAocLetterElement
    'aoc-app': HTMLAocAppElement
  }

  interface ElementTagNameMap {
    'aoc-letter': HTMLAocLetterElement;
    'aoc-app': HTMLAocAppElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
